version: "3.8"

services:
  minio:
    container_name: minio-server
    image: minio/minio:latest
    ports:
      - "9000:9000"     # API
      - "9001:9001"     # Web UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniol23
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    #restart: always

  researcher_cli:
    container_name: researcher_cli
    image: python:3.9-slim-buster
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null 
    depends_on:
      - minio

volumes:
  minio-data:
    name: projects_minio-data