version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"   # API MinIO
      - "9001:9001"   # Console MinIO
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniol23
    command: server /data --console-address ":9001"
    networks:
      - bigdata

volumes:
  minio-data:

networks:
  bigdata:
    driver: bridge
